import { cpSync, mkdirSync, readFileSync, writeFileSync, existsSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'web');
const files = ['index.html', 'styles.css', 'app.js', 'manifest.json', 'icon.svg', 'privacy.html'];

function readApiUrl(filePath) {
  const lines = readFileSync(filePath, 'utf8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('//')) continue;
    const m = trimmed.match(/ADHD_FLOW_API\s*=\s*['"]([^'"]*)['"]/);
    if (m) return m[1];
  }
  return '';
}

let apiUrl = '';
if (process.env.VERCEL) {
  apiUrl = '';
} else if (existsSync(join(root, 'config.local.js'))) {
  apiUrl = readApiUrl(join(root, 'config.local.js'));
} else if (existsSync(join(root, 'config.example.js'))) {
  apiUrl = readApiUrl(join(root, 'config.example.js'));
}

const configJs = `// Auto-generated by scripts/sync-www.mjs\nwindow.ADHD_FLOW_API = '${apiUrl}';\n`;

for (const destName of ['www', 'public']) {
  const dest = join(root, destName);
  mkdirSync(dest, { recursive: true });
  for (const file of files) {
    if (file === 'config.js') continue;
    cpSync(join(src, file), join(dest, file));
  }
  writeFileSync(join(dest, 'config.js'), configJs);
}

console.log('Synced www/ + public/ from web/');
console.log('API base:', apiUrl || '(same-origin)');
