import { cpSync, mkdirSync, readFileSync, writeFileSync, existsSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const portalRoot = process.env.PORTAL_ROOT || join(root, '..', 'public', 'adhd-flow');
const src = join(root, 'web');
const files = ['index.html', 'styles.css', 'app.js', 'manifest.json', 'icon.svg', 'privacy.html'];

const API_URL =
  process.env.ADHD_FLOW_API ||
  (existsSync(join(root, 'config.example.js'))
    ? readFileSync(join(root, 'config.example.js'), 'utf8').match(/ADHD_FLOW_API\s*=\s*['"]([^'"]*)['"]/)?.[1]
    : '') ||
  'https://adhd-flow-ios.vercel.app';

mkdirSync(portalRoot, { recursive: true });

for (const file of files) {
  let content = readFileSync(join(src, file), 'utf8');
  if (file === 'index.html') {
    content = content
      .replace(/href="\/manifest\.json"/g, 'href="/adhd-flow/manifest.json"')
      .replace(/href="\/icon\.svg"/g, 'href="/adhd-flow/icon.svg"')
      .replace(/href="\/styles\.css"/g, 'href="/adhd-flow/styles.css"')
      .replace(/src="\/config\.js"/g, 'src="/adhd-flow/config.js"')
      .replace(/src="\/app\.js"/g, 'src="/adhd-flow/app.js"');
  }
  if (file === 'manifest.json') {
    const json = JSON.parse(content);
    json.start_url = '/adhd-flow/';
    json.icons = (json.icons || []).map((icon) => ({
      ...icon,
      src: icon.src?.startsWith('/') ? `/adhd-flow${icon.src}` : `/adhd-flow/${icon.src}`,
    }));
    content = `${JSON.stringify(json, null, 2)}\n`;
  }
  writeFileSync(join(portalRoot, file), content);
}

writeFileSync(
  join(portalRoot, 'config.js'),
  `// Auto-generated by lifeflow/scripts/sync-portal.mjs\nwindow.ADHD_FLOW_API = '${API_URL}';\n`
);

console.log('Synced portal →', portalRoot);
console.log('API base:', API_URL);
